services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn bot:app"
    envVars:
      - key: BOT_TOKEN
        value: 8037078100:AAGZ7p8c0T1uz5VkJE6wJi6dWBqlsrUxM-s
